name: Web Application Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and Build
      run: |
        echo "=== Building Project ==="
        npm install
        npm run build

    - name: Deploy to Web Server
      run: |
        echo "=== Deploying to Web Server ==="
        cp -R dist/* /var/www/html/
        echo "Deployment Successful!"